# Generated by Django 4.0.4 on 2022-05-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_airport_alter_flight_destination_alter_flight_orign'),
    ]

    operations = [
        migrations.CreateModel(
            name='passanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flight', models.ManyToManyField(blank=b'I01\n', related_name='passanger', to='flights.flight')),
            ],
        ),
    ]
